name: Code Coverage

on:
  push:
    branches: [ master, dev , feat/*]
  pull_request:
    branches: [ master ]

jobs:
  per-python:
    name: Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]

    uses: ./.github/workflows/_test-os-arch.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit
