name: Code Coverage

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v4.1
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - run: pdm install
        shell: bash
      - name: Run tests
        run: pdm run pytest -s
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PYTHON_VERSION
